FROM golang:1.16.0-alpine

ENV CGO_ENABLED=0

RUN apk update && \
    apk add --no-cache git 

#RUN go get -u github.com/labstack/echo && \
#    go get -u github.com/labstack/echo/middleware && \
#    go get -u github.com/lib/pq && \
#    go get -u gorm.io/gorm
