version: '3'

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./docker/golang/Dockerfile
    ports:
      - 1323:1323
    volumes:
      - .:/money-send-api
    working_dir: /money-send-api
    tty: true
    depends_on: 
      - postgres

  postgres:
    container_name: postgres
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin_pass
      - POSTGRES_DB=app
